### ISSUE TITLE
More hash collision between atoms

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1739]
This is a continuation of issue #1625 with a list of new atom collisions. I suspect most, if not all, exhibit pathologies in the hash algorithm as opposed to being part of the random set of unavoidable collisions.

So here's the list

- [x] No longer colides
```
(SequentialAndLink
  (AbsentLink
    (EvaluationLink
      (PredicateNode "visible") ; [7535041300660910155][1]
      (ListLink
        (VariableNode "$x") ; [788143063270552312][1]
      ) ; [10028350822169473443][1]
    ) ; [11397036793678782603][1]
  ) ; [11424322274233087092][1]
  (EvaluationLink
    (GroundedPredicateNode "scm: incr-trig") ; [409184162435433586][1]
    (ListLink
    ) ; [9223882210250052939][1]
  ) ; [15246955578542806330][1]
) ; [14915126413073086491][1]
```
with
```
(SequentialOrLink
  (PresentLink
    (EvaluationLink
      (PredicateNode "visible") ; [7535041300660910155][1]
      (ListLink
        (VariableNode "$x") ; [788143063270552312][1]
      ) ; [10028350822169473443][1]
    ) ; [11397036793678782603][1]
  ) ; [11423741732093633805][1]
  (EvaluationLink
    (GroundedPredicateNode "scm: incr-trig") ; [409184162435433586][1]
    (ListLink
    ) ; [9223882210250052939][1]
  ) ; [15246955578542806330][1]
) ; [14915126413073086491][1]
```
- [x] No longer collides
```
(BindLink
  (TypedVariableLink
    (GlobNode "$star") ; [7221702073207368645][1]
    (IntervalLink
      (NumberNode "0.000000") ; [4895729370997130312][1]
      (NumberNode "1.000000") ; [2263783472620955547][1]
    ) ; [18413741763871150138][1]
  ) ; [9806233150850800417][1]
  (ListLink
    (ConceptNode "I") ; [8053501913945070544][1]
    (ConceptNode "love") ; [5772868835305624798][1]
    (GlobNode "$star") ; [7221702073207368645][1]
  ) ; [11983067370852204958][1]
  (ListLink
    (ConceptNode "Hey!") ; [518141375632718247][1]
    (ConceptNode "I") ; [8053501913945070544][1]
    (ConceptNode "like") ; [7248936160044154347][1]
    (GlobNode "$star") ; [7221702073207368645][1]
    (ConceptNode "also") ; [5336304934127728681][1]
  ) ; [12166051098100620379][1]
) ; [16336166235471976395][1]
```
with
```
(BindLink
  (ListLink
    (ConceptNode "I") ; [8053501913945070544][1]
    (ConceptNode "love") ; [5772868835305624798][1]
    (GlobNode "$star") ; [7221702073207368645][1]
  ) ; [11983067370852204958][1]
  (ListLink
    (ConceptNode "Hey!") ; [518141375632718247][1]
    (ConceptNode "I") ; [8053501913945070544][1]
    (ConceptNode "like") ; [7248936160044154347][1]
    (GlobNode "$star") ; [7221702073207368645][1]
    (ConceptNode "also") ; [5336304934127728681][1]
  ) ; [12166051098100620379][1]
) ; [16336166235471976395][1]
```
- [x] No longer collides (however a unit test is missing, due to requiring nlp, this link is ill-formed anyway)
```
(SimilarityLink
  (NumberNode "0.240000") ; [4131614200759358872][1]
  (PrepositionalRelationshipNode "Big Red Button") ; [7813933594493059977][1]
  (ExecutionLink (stv 1.000000 1.000000)
    (GroundedSchemaNode "ActivationModulatorUpdater") ; [8598634016184033070][1]
    (ListLink
      (LemmaNode "thing1") ; [509783609095519846][1]
      (LemmaNode "thing2") ; [6666218316305125129][1]
      (LemmaNode "thing3") ; [74745372477125905][1]
    ) ; [9561778288985680523][1]
  ) ; [18378065652795676925][1]
) ; [10763015415641857427][1]
```
with
```
(SimilarityLink (stv 1.000000 1.000000)
  (NumberNode "0.240000") ; [4131614200759358872][1]
  (GroundedSchemaNode "ActivationModulatorUpdater") ; [8598634016184033070][1]
  (ExecutionLink (stv 1.000000 1.000000)
    (PrepositionalRelationshipNode "Big Red Button") ; [7813933594493059977][1]
    (ListLink
      (LemmaNode "thing1") ; [509783609095519846][1]
      (LemmaNode "thing2") ; [6666218316305125129][1]
      (LemmaNode "thing3") ; [74745372477125905][1]
    ) ; [9561778288985680523][1]
  ) ; [10929695810703116472][1]
) ; [10763015415641857427][1]
```
- [x] No longer collides
```
(TimesLink
  (NumberNode "5.000000") ; [2039579538807236167][1]
  (PlusLink
    (NumberNode "3.000000") ; [2390611616569436914][1]
    (ValueOfLink
      (ConceptNode "some atom") ; [8471632823165217328][1]
      (PredicateNode "my key") ; [4506835830485469207][1]
    ) ; [9687662652131341782][1]
  ) ; [17185606029329362355][1]
) ; [13137806621578675219][1]
```
with
```
(PlusLink
  (NumberNode "5.000000") ; [2039579538807236167][1]
  (TimesLink
    (NumberNode "3.000000") ; [2390611616569436914][1]
    (ValueOfLink
      (ConceptNode "some atom") ; [8471632823165217328][1]
      (PredicateNode "my key") ; [4506835830485469207][1]
    ) ; [9687662652131341782][1]
  ) ; [17223921810533279297][1]
) ; [13137806621578675219][1]
```

**Comment by ngeiswei** [comment]
All collisions presented in issue #1625 have been resolved however that issue contains valuable information, may provide hints to fix the problem and recall the necessity to add unit tests.

**Comment by linas** [comment]
Yes, there is something pathologically wrong with the hash function. Those collisions are implausible for a good hash function.

It appears to be related to the atom type: case 4. in particular makes this clear: although the atom types were swapped, the hash came out the same.  This implies that the atom types are not being hashed in correctly.

**Comment by linas** [comment]
Yes, I think I see. I'll try to fix this now.

The Links still use the old, known-poor avalanching code. The guy who fixed the ScopeLink hash did not think of going back and also doing it for Links in general.

**Comment by linas** [comment]
Actually, I will NOT try to fix this now. Let someone else do it. The fix is "easy": 

1) Edit ScopeLink.cc remove the fnv1a hash code lines 241 to 283, and put them into a file `opencog/atoms/base/hash.h`
2) `#include hash.h` in ScopeLink.cc
3) `#include hash.h` in Link.cc
4) Edit Link.cc replace line 170 with fnv1a

**Comment by linas** [comment]
Pull req #1741 should fix this.  I did not check for other hash collisions.

I went ahead and did this, because the hashing code is in a 
performance-critical path (which is why, initially, it implemented 
a weak hash to begin with) and I'm concerned that fancier hashes
will degrade performance.  (viz. that my above suggestion of using
fnv1a in Link.cc will hurt link-creation performance, which is already
quite slow.)

**Comment by noskill** [comment]
It is possible to speed up fnv1a_hash by doing less mixing, I'll see if it is worth doing.

**Comment by ngeiswei** [comment]
BTW, unit tests are still missing for the collisions recently fixed...

**Comment by ngeiswei** [comment]
@noskill if you still have the stamina to fix the remaining failing scope link `HashUTest::test_scope_compute_hash_4()` that'd be awesome.

**Comment by noskill** [comment]
@ngeiswei Ok, working on it..
