### ISSUE TITLE
Assertion `PyBytes_Check(pyErrorString)' failed

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/atomspace#1886]
Running `~/opencog/atomspace/examples/atomspace.python.scm` leads to the following output ending in an error:

```
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /opencog/atomspace/examples/atomspace/python.scm
;;; compiled /.cache/guile/ccache/2.2-LE-8-3.A//opencog/atomspace/examples/atomspace/python.scm.go
hello! 4
guile: /tmp/atomspace-master/opencog/cython/PythonEval.cc:632: void opencog::PythonEval::build_python_error_message(const char*, std::__cxx11::string&): Assertion `PyBytes_Check(pyErrorString)' failed.
```

So, the `(use-module (opencog-python))` and `(python-eval "print("something")")` parts work, but the `exec(open)` part doesn't.

ETA: looks like Linas has run into this at least once: [here](https://github.com/opencog/atomspace/issues/1707#issuecomment-404715770)

**Comment by noskill** [comment]
I fixed error extraction in this PR https://github.com/opencog/atomspace/pull/1887
Should give more meaningful messages now

**Comment by linas** [comment]
Still an issue, but a bit different now. the exec fails with:
```
scheme@(guile-user)> (python-eval "exec(open('my_py_func.py'))")
ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("python-eval" "Python error: exec() arg 1 must be a string, bytes or code object.\nTraceback: <traceback object at 0x7ff7efacad88> (/home/linas/src/novamente/src/atomspace-git/opencog/cython/PythonEval.cc:684)\nFunction args:\n(exec(open('my_py_func.py')))")'.
```

changing it to quote the open silently fails:
```
(python-eval "exec(\"open('my_py_func.py')\")")
```
but fails later.   Doing things by hand:
```
 (python-eval "
from opencog.atomspace import AtomSpace, TruthValue
from opencog.atomspace import types

asp = AtomSpace()

# Python function taking two atoms, converting thier string-names to
# floats, adding the floats, and returning a new atom holding the sum.
def my_py_func(atoma, atomb):
    print('Python received two arguments:\n' + str(atoma) + str(atomb))
    av = float(atoma.name)
    bv = float(atomb.name)
    cv = av + bv       # Add numeric values!
    print('The sum is ' + str(cv))
    return asp.add_node(types.ConceptNode, str(cv))

")
ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("python-eval" "Python error: ('EOL while scanning string literal', ('<string>', 5, 42, \"    print('Python received two arguments:\\n\")). (/home/linas/src/novamente/src/atomspace-git/opencog/cython/PythonEval.cc:684)\nFunction args:\n(\nfrom opencog.atomspace import AtomSpace, TruthValue\nfrom opencog.atomspace import types\n\nasp = AtomSpace()\n\n# Python function taking two atoms, converting thier string-names to\n# floats, adding the floats, and returning a new atom holding the sum.\ndef my_py_func(atoma, atomb):\n    print('Python received two arguments:\n' + str(atoma) + str(atomb))\n    av = float(atoma.name)\n    bv = float(atomb.name)\n    cv = av + bv       # Add numeric values!\n    print('The sum is ' + str(cv))\n    return asp.add_node(types.ConceptNode, str(cv))\n\n)")'.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
```
looks like the single-quote got escaped incorrectly. Bizarre. Investigating

**Comment by linas** [comment]
Fixed it. Its a python3 portability issue Need to say 
```
(python-eval "exec(open('my_py_func.py').read())")
```

**Comment by linas** [comment]
Closing; I'm pretty sure this is now fixed.
