### ISSUE TITLE
TypeChoice fails over some pattern

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#950]
See the unit added in #949 to reproduce it.

**Comment by ngeiswei** [comment]
It is tied to this line

https://github.com/opencog/atomspace/blob/master/opencog/query/DefaultPatternMatchCB.cc#L295

I have to admit I don't understand it...

**Comment by ngeiswei** [comment]
It's not related to `TypeChoice` it's related to `ScopeLink` again, I can reproduce it in a simpler way as follows:

```
scheme@(guile-user)> (ForAllLink (VariableNode "$X") (EvaluationLink (Predicate "P") (VariableNode "$X")))
scheme@(guile-user)> (define gl (Get (ForAllLink (Variable "$X") (Variable "$B"))))
scheme@(guile-user)> (cog-satisfying-set gl)
$3 = (SetLink
)
```

**Comment by ngeiswei** [comment]
F###, this variation works:
```
scheme@(guile-user)> (ForAllLink (VariableNode "$X") (EvaluationLink (Predicate "P") (VariableNode "$X")))
scheme@(guile-user)> (define gl (Get (ForAllLink (Variable "$V") (Variable "$B"))))
scheme@(guile-user)> (cog-satisfying-set gl)
$3 = (SetLink
   (ListLink
      (VariableNode "$X")
      (EvaluationLink
         (PredicateNode "P")
         (VariableNode "$X")
      )
   )
)
```
???

It seems the on the fly alpha-conversion is kinda messing stuff. I have to say I'm not sure this is a good idea, it is utterly confusing for the user to enter an atom and see in return its variable renamed, utterly...

**Comment by ngeiswei** [comment]
Well, the first one failing actually makes sense because the Variable "$X" doesn't self-match. However this shows how this plays so badly with on-the-fly alpha-conversion. Imagine that one enters first a pattern using "$X", then enters the same pattern using "$V" to hopefully avoid colliding with "$X" is some grounds to match, then it will silently fail. The user would have to delete first the pattern with "$X" then re-enter the one with "$V".

**Comment by linas** [comment]
I'll take a look at this tomorrow. From your description, there is a bug in the self-matching code: its not actually a self-match, if the thing being matched is alpha-convertible to something else.  Of course, easy to say, harder to do.  The self-matching code is very very old, dating back to the beginning, long before lambda and scope links got introduced. So -- no surprise that it now does the wrong thing.

**Comment by linas** [comment]
FWIW: its a "known bug": there is even an old comment in the code that talks about this bug: https://github.com/opencog/atomspace/blob/master/opencog/query/PatternMatchEngine.cc#L100-L110

**Comment by linas** [comment]
I'm working on fixing this.  Its taking a lot longer than I expected -- day two is almost over and I'm not done yet.   Am tryig to handle self-grounding correctly, but there's a lot of complex corner cases. Ugh.

**Comment by linas** [comment]
Oof. It took way too long, but I am finally back to where I started, and will be able to fix this shortly.

**Comment by linas** [comment]
OK, so Pull req #965 should fix this.

**Comment by ngeiswei** [comment]
That seems awesome. However the test is still failing, I've tried to wrap the ForallLink in quote link #966, which makes sense to me, but it still fails.

**Comment by linas** [comment]
I am starting to really really hate quotelink.

**Comment by linas** [comment]
OK, so pull req #967 fixes this for me. The key is that, during searches, the "PatternTerm" invented by @jswiergo  helps contextualize whether something is in quotes, or not. Without it, walking up and down the pattern trees becomes a real mess.  

Thank you @jswiergo  for that fix -- I realize it was probably quite hard to implement it correctly, but it seems to have been the right thing to do.

**Comment by ngeiswei** [comment]
Awesome, thanks!
